name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;files,${{github.workspace}}/build/vcpkg_binary_cache,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        compiler: [ g++, clang++ ]

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/build/vcpkg_binary_cache
          key: ${{ matrix.os }}-${{ matrix.compiler }}

      - name: Configure CMake
        run: cmake -GNinja -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
