name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;files,${{github.workspace}}/build/vcpkg_binary_cache,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-20.04, cc: gcc, cxx: g++}
          - {os: ubuntu-20.04, cc: clang, cxx: clang++}
          - {os: windows-latest, cc: cl, cxx: cl}
          - {os: windows-latest, cc: gcc, cxx: g++}
          - {os: macos-latest, cc: gcc, cxx: g++}
          - {os: macos-latest, cc: clang, cxx: clang++}

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/build/vcpkg_binary_cache
          key: ${{ matrix.os }}-${{ matrix.cxx }}

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}
